### ISSUE TITLE
Problem Statement Review for Coverage

### ISSUE THREAD

**Issue by sorainsm** [sorainsm/library-of-lighting-models#1]
Please take a cursory look to see if I've addressed the problem in an abstract manner. I think I'm confusing my problem statement for this course (which should abstractly be about the physical problem) with the type of problem statement I'd write for my thesis (which has an element of my proposed work in it). Feedback would be appreciated!

**Comment by smiths** [comment]
Hello @sorainsm.  Your problem statement seems at the correct level of abstraction to me.  You haven't mentioned any specific implementation details.
