### ISSUE TITLE
Question about the relationship between assumptions and models

### ISSUE THREAD

**Issue by sharyuwu** [sorainsm/library-of-lighting-models#14]
@sorainsm 
Can you please explain the relationship between Dot Product of two n-dimensional vectors( DD1 ) and AB1, AB2?
Base on the description of AB1 and AB2, I think it states that this library is only considering the 3 dimensions(3D) problems. Please correct me if I wrong.

Therefore, is it means that in the equation of DD1, the n-dimensional vectors where "n" is at most 3?

![image](https://user-images.githubusercontent.com/55363335/67138205-ef03a180-f20d-11e9-95e0-4c1b3f354164.png)

**Comment by smiths** [comment]
@sharyuwu, I believe that @sorainsm is using DD1 to specify the general concept of dot product.  This concept applies to n-dimensional vectors.  The more general way of writing this is better than specifying 3 dimensional vectors, because someone else can reuse this definition in their document.
