### ISSUE TITLE
Enhance the description

### ISSUE THREAD

**Issue by sharyuwu** [sorainsm/library-of-lighting-models#16]
@sorainsm 
Can you please define the meaning of Ld in this equation. The definition of Ld could not be found in this document.

![image](https://user-images.githubusercontent.com/55363335/67138633-8c61d400-f214-11e9-940b-50085a7faa66.png)

**Comment by sharyuwu** [comment]
Same issue here, the definition of Ls had not been explained.

![image](https://user-images.githubusercontent.com/55363335/67149530-3758a900-f27a-11e9-8fad-9b96dc5678ed.png)

**Comment by sorainsm** [comment]
Thanks for the catch @sharyuwu ! 
Seems like I got some of my symbols mixed up.
The data definitions are now correct, with all the symbols explained.
Changes made in : cb95e52e54dcfd0b1df559731131bd8280acd53e
