### ISSUE TITLE
Add a .gitignore file to your project

### ISSUE THREAD

**Issue by smiths** [sorainsm/library-of-lighting-models#17]
Please add a .gitignore file so that git can ignore generated files.  Sample .gitignore files are given in the BlankProjectTemplate.

**Comment by sorainsm** [comment]
Borrowed your .gitgnore file from the BlankProjectTemplate. Removed code file extensions since they aren't relevant to my project. I'll continue to modify it based on the output files of my code.

Resolved in **d34bc47e16c350fe5dd88c2c0d05c01e0dc8af47**

**Comment by smiths** [comment]
Looks good.
