### ISSUE TITLE
Question: how does the data definition drive the instance model?

### ISSUE THREAD

**Issue by sharyuwu** [sorainsm/library-of-lighting-models#18]
@sorainsm 
Followed by https://github.com/sorainsm/library-of-lighting-models/issues/13, without the equation in IM, it is hard to how does the output is driven by other equations.
The question here is that is IM1 driven by DD3?
Based on the output and description of IM1, I can see how DD2 is implied, but I can not comprehend why IM1 needs DD3, where defining the value of Ia.

![image](https://user-images.githubusercontent.com/55363335/67149192-476e8980-f276-11e9-98db-af3c798339f7.png)

![image](https://user-images.githubusercontent.com/55363335/67149202-52c1b500-f276-11e9-8cbf-520278a300f1.png)

![image](https://user-images.githubusercontent.com/55363335/67149208-679e4880-f276-11e9-994d-959e341b717b.png)

**Comment by sorainsm** [comment]
I've added equations to the IMs that should clarify this in cb95e52e54dcfd0b1df559731131bd8280acd53e.

This was also addressed in https://github.com/sorainsm/library-of-lighting-models/issues/13#issuecomment-549658597
