### ISSUE TITLE
System VnV 2.3 Abbreviations and Acronyms

### ISSUE THREAD

**Issue by peter-michalski** [sorainsm/library-of-lighting-models#24]
"Family of Lightning Symbols" as both symbol and description

Was this supposed to be FLS? However do not see any FLS in the document.

**Comment by sorainsm** [comment]
Removed from symbols list. It was there originally for references to the software being designed, but as the command \famname makes the repetition of it easy to type without losing meaning, I have elected to remove it from the symbol list  in the document.
