### ISSUE TITLE
MG/MIS Question: Where to Put Data Type Modules

### ISSUE THREAD

**Issue by sorainsm** [sorainsm/library-of-lighting-models#42]
@smiths we discussed during my presentation that the data types should be their own modules. Where would these modules be captured in the module guide? My intuition is that they'd be listed with behaviour hiding modules, but since they're just types there's an argument for them being generic enough for anyone to use (e.g. how to represent points in 3D space, or colours).

**Comment by smiths** [comment]
The answer to this question depends on the types.  If they are abstract data types (ADTs), then the behaviour of the objects could come from the SRS. In that case, they are behaviour hiding.  If the behaviour is not related to the SRS, then software decision hiding makes sense.

For record types (no behaviour, just data), the classification again depends.  If the type is introduced in the SRS, it would be behaviour hiding.  If the type is not introduced in the SRS, it is software decision hiding.
