### ISSUE TITLE
MG + MIS Ready for Review

### ISSUE THREAD

**Issue by sorainsm** [sorainsm/library-of-lighting-models#43]
Hi everyone, sorry for the delay.
The MG + MIS are now ready for review.
I was having a weird compilation issue with my TeX editor (TeXStudio) and for some reason the module uses hierarchy image in my repo is not showing up. If anyone can spot why that would be appreciated!

**Comment by smiths** [comment]
Comments on the MG are in f1f1ca779f2570b97b5d6c4eb331acaf92a2f71e.  Comments on the MIS are in c940b48d6860abbee5950c0fab5d4d6542e6b5b6.

**Comment by smiths** [comment]
I see that @deemaalomair1 and @peter-michalski have provided their comments as well, so I will close this issue.
