### ISSUE TITLE
Primary Reviewer Module to Implement

### ISSUE THREAD

**Issue by peter-michalski** [sorainsm/library-of-lighting-models#54]
Hi @sorainsm, please let me know what you would like me to implement.

**Comment by sorainsm** [comment]
Hi Peter,

Sorry for the late reply.
Could you please implement Vector module in a language of your choosing (whichever you know best)?

I have talked with @smiths  and most of the modules that I have documented are built into the system that I'm using, meaning that the only parts to implement would require learning the Unity Shader Language. As such, we agreed that you could implement the Vector module in whatever language you feel comfortable so as to get feedback on how well the module guide explains the module.

**Comment by peter-michalski** [comment]
I have added a C# implementation in 7747a863fa6cf6ca84b3179b405465bf841bb913.  

Vector appears to be a class. 
I was unsure how to proceed with the start() function.

**Comment by smiths** [comment]
I haven't done a detailed comparison between the spec and the code, but I'm encouraged by what I see.  This seems like a successful experiment.  @sorainsm, it isn't required for CAS 741, but when you review the work of @peter-michalski, I would be curious to hear about any differences you observe between the spec and the implementation.
