### ISSUE TITLE
Final Submission

### ISSUE THREAD

**Issue by sorainsm** [sorainsm/library-of-lighting-models#55]
Hi @smiths I don't have it in me to continue on this documentation with the current time restrictions.
I've made updates to the Commonality Analysis, and System VnV and filled in a Unit VnV Plan and  the beginnings of a System VnV Test Report.

I have also filled out the Reflection.

My code is in the src folder and you can find an executable at:
https://www.cas.mcmaster.ca/~sorainsm/projects/index.html

Makes it easier to play around with in a browser instead of having to install and run it on your system.

Have a wonderful holiday!

**Comment by smiths** [comment]
Thank you @sorainsm.  Enjoy your holidays too!

**Comment by smiths** [comment]
@sorainsm, is all of your source code under version control?  I am able to view  your executable through the link you provided above, but I cannot find any files that look like they were used to build this executable.  I was hoping to have a look from Unity (I'm not an expert, but I have used it to run student projects in the past), but you don't seem to have enough files to work with it?

**Comment by smiths** [comment]
I am asking because grading the source code is part of the final evaluation, so I would like to have a look at code you have written.

**Comment by sorainsm** [comment]
The whole Unity project is under version control.

To open it in Unity you would open the whole project folder which is named ShaderTutorial. Don't mind the name, I had started it as a project to follow a tutorial and then ended up just continuing to work with that project to expand it out.

The ShaderTutorial project is under src/shaderTesting

If you would just like to look at the behaviour scripts that I implemented (Shaders and Lighting) you can find them in src/shaderTesting/ShaderTutorial/Assets/Scripts

**Comment by smiths** [comment]
Thank you @sorainsm.
