### ISSUE TITLE
CA Review: Data Definitions

### ISSUE THREAD

**Issue by sorainsm** [sorainsm/library-of-lighting-models#6]
Please take a close look at the Data Definitions.
I am unsure whether DD8-10 should be Data Definitions or whether I should have listed DD8 as a Theoretical Model, with DD9-10 being general definitions or instance models of this.

![image](https://user-images.githubusercontent.com/11723492/66450151-75a5cb00-ea25-11e9-9b9b-154893283325.png)
![image](https://user-images.githubusercontent.com/11723492/66450172-83f3e700-ea25-11e9-9f44-fcf687a9a6de.png)

**Comment by smiths** [comment]
@sorainsm, you should assign this issue to someone, even if your intention is to self-assign the issue.  Maybe you are intending to assign it to your primary or secondary reviewer?

**Comment by sorainsm** [comment]
@smiths I'm waiting on my primary and secondary to accept the invite as collaborators.
I will assign this to myself for now, and reassign once they accept.

**Comment by smiths** [comment]
Makes sense.  :smile:

**Comment by peter-michalski** [comment]
Sorry I started creating issues before accepting the invite. Just noticed this now. I'll take a look!

**Comment by peter-michalski** [comment]
@sorainsm I think that your current placement is correct. As far as I can tell DD9 is not derived from DD8, it only uses a variable from it. I am assuming that the relationship is the same for DD10
