### ISSUE TITLE
CA Review: Assumptions and Traceability

### ISSUE THREAD

**Issue by sorainsm** [sorainsm/library-of-lighting-models#7]
Please review whether the assumptions I've listed are reasonable and if they require more justification.

They seem logical and obvious to me, however I've become too close to the project to tell. I'm also hesitant that I've got no run-time binding assumptions listed. A previous issue can show that I moved what I thought were run-time bindings to input variabilities. [EDIT: it was issue #3]

![image](https://user-images.githubusercontent.com/11723492/66450202-a8e85a00-ea25-11e9-85d1-e07f0a324e80.png)
![image](https://user-images.githubusercontent.com/11723492/66450217-b1d92b80-ea25-11e9-8eac-4030a6d9d5fd.png)

**Comment by sharyuwu** [comment]
@sorainsm 
I am halfway through your document, and so far, I felt the assumption here is reasonable. You do need these assumptions to emphasize what kind of cases this library can implement or address.
Just like Doctor smith replied in this issue https://github.com/sorainsm/library-of-lighting-models/issues/14, placing a variable inside the equation first; then defining the assumption can concrete the reusability of this document.

**Comment by sorainsm** [comment]
Thanks for the feedback @sharyuwu 
I have actually changed my assumptions based on feedback from Dr. Smith.

@smiths if you could review the new assumptions in cb95e52e54dcfd0b1df559731131bd8280acd53e to see whether they are appropriate I would appreciate it. I'm concerned I didn't quite understand your feedback about invoking assumptions and other assumptions taking their place if the listed ones were not invoked.

I had understood the assumptions as being the design decisions that we were making to scope the project down from abstract - therefore all of the assumptions I had previously listed **were** my design decisions. That's why I was confused about how to write down what family member I was going to build - I was under the impression that my listed assumptions already gave that information to the reader.

My new assumptions cover more design decisions, but I've listed alternate assumption that could take their place (i.e. be likely changes) in a different family member. I don't know how to capture that information appropriately in the template - or how to abstract the decision that each assumption makes in a way that captures all the possibilities.

Any advice would be appreciated! 😄

**Comment by smiths** [comment]
@sorainsm, your assumptions definitely look better.  The assumptions are in the Variabilities section, which is why there should be alternative assumptions, or the option of including or excluding an assumption.  Differences in assumptions is what distinguishes one family member from another.
